### ISSUE TITLE
BACK END - ANDROID compilation error

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#12]
When trying to compile for andoid get this error 

peter@PETERILLIAS MINGW64 ~/Documents/GitHub/zoraFitApp (master)
$ cordova run android --verbose
No scripts found for hook "before_run".
Executing script found in plugin cordova-plugin-ionic for hook "before_prepare": plugins\cordova-plugin-ionic\hooks\beforePrepare.js
Generating initial manifest for Ionic Deploy...
Ionic Deploy initial manifest successfully generated.
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Android Studio project detected
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\app\src\main\res\xml\config.xml
config file res/values/facebookconnect.xml requested for changes not found at C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\res\values\facebookconnect.xml, ignoring
config file res/values/facebookconnect.xml requested for changes not found at C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\res\values\facebookconnect.xml, ignoring
config file res/values/facebookconnect.xml requested for changes not found at C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\res\values\facebookconnect.xml, ignoring
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [www, platforms\android\platform_www] to platforms\android\app\src\main\assets\www
  copy  www\pro-manifest.json platforms\android\app\src\main\assets\www\pro-manifest.json (updated file)
Wrote out android application name "Zora Fit" to C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\app\src\main\res\values\strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (0.0.1): 1
Wrote out Android package name "zora.fit" to C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\app\src\main\java\zora\fit\MainActivity.java
Updating icons at platforms\android\app\src\main\res
Updating splash screens at platforms\android\app\src\main\res
This app does not have additional resource files defined
Prepared android project successfully
Executing script found in plugin cordova-plugin-facebook4 for hook "after_prepare": plugins\cordova-plugin-facebook4\scripts\after_prepare.js
ANDROID_HOME=C:\Users\peter\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\java\jdk1.8.0_191
studio
Subproject Path: CordovaLib
Subproject Path: app
Running command: cmd "/s /c "C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m""
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Command finished with error code 1: cmd /s /c "C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m"
cmd: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Error: cmd: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
    at ChildProcess.whenDone (C:\Users\peter\Documents\GitHub\zoraFitApp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

peter@PETERILLIAS MINGW64 ~/Documents/GitHub/zoraFitApp (master)
$

**Comment by cediim8** [comment]
Hi Peter, I cannot reproduce this issue on my end, on both my computers. I however found this ([https://github.com/NativeScript/NativeScript/issues/5188](https://github.com/NativeScript/NativeScript/issues/5188)) that might have a solution. Let me know if that helps, otherwise we'll have to investigate a little further. Thanks. Cedric

**Comment by peterillias** [comment]
Perfect  ! seems to work. Do you have recommended set of commands to compile app for final use ?
I am using ionic cordova run android -l right now


![image](https://user-images.githubusercontent.com/22891710/53731808-36564100-3e7c-11e9-98e9-35f52b8fb80f.png)

**Comment by cediim8** [comment]
Awesome, I'm glad! You can use the following APK built for testing on a real device. When it comes time for production, we can run a release build and sign the APK, but it is not necessary for now in my opinion.
