### ISSUE TITLE
FRONT END - Language change

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#15]
What is easiest way to test SK language ? i changed EN for SK but nothing happend

  setAppLanguage() {
    this.storage.get('language').then((val: string) => {
      if (val != null) {
        this.translateService.setDefaultLang(val);
        this.translateService.use(val);
      } else {
        this.translateService.setDefaultLang('en');
        this.translateService.use('en');

        this.storage.set('language', 'en');
      }
    });
  }

**Comment by cediim8** [comment]
Hi Peter, on your profile there is a ‘Language’ setting that I’ve added to change the current language. Please try it, it should work. Thanks. Cedric
