### ISSUE TITLE
FRONT END - Category description

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#19]
Category description text is as WHITE in CSS but still dark in app. Please check.

![image](https://user-images.githubusercontent.com/22891710/54378758-51009500-4688-11e9-8cd4-18c08c5dd80a.png)

**Comment by cediim8** [comment]
Hi Peter, you requested that most of the descriptions, including the one in categories be from HTML set in the back end. In this case, the style set in the back end is hard coded and cannot be overridden by the CSS. Unfortunately, this is what I warned of by allowing front end style to be set from the back end. 

![image](https://user-images.githubusercontent.com/31234136/54663181-17b6a200-4b2c-11e9-99dd-14661fdc5342.png)
