### ISSUE TITLE
BACK END - Sort

### ISSUE THREAD

**Issue by peterillias** [cediim8/zoraFitApp#20]
Please add sort option to categories and videos so i can sort items as i want them to be displayed in front end

![image](https://user-images.githubusercontent.com/22891710/54379011-dedc8000-4688-11e9-8f3a-a721fb90c672.png)

**Comment by cediim8** [comment]
Hi Peter, the list of videos in the 'Videos' section doesn't have any order but once added to a category, you will see that I have added the ability to now change the order of videos in the front end.

![image](https://user-images.githubusercontent.com/31234136/54663515-3ff2d080-4b2d-11e9-85a0-0e97ea50c47d.png)

![image](https://user-images.githubusercontent.com/31234136/54663524-4b45fc00-4b2d-11e9-8d4f-2d235babb2fd.png)
